name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  release:
    types: [created]
  workflow_dispatch: # Put here!!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up CI environment
        run: .github/setup.sh
      - name: Execute the build
        run: .github/build.sh
        env:
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
          SIGNING_ASC: ${{ secrets.SIGNING_ASC }}
      - run: ls /home/runner/work/mpicbg/mpicbg/mpicbg_/target
      - run: mkdir staging && cp .m2/repository/mpicbg/mpicbg/1.5.1-SNAPSHOT/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
